---
- hosts: all
  become: yes
  tasks:
  - name: Run docker-compose up
     # become: false
      # command: "{{ item }}"
    shell: 
      cmd: "docker-compose -f /home/vagrant/data/docker-compose.yml up -d" #with shell command we use docker-compose up command
